### PR TITLE
Added LogSerial class

### PR DESCRIPTION
**Pull request by kenj1**
New class to support printf style log messaging.  Detailed description in top of LogSerial.h comments.

### CODE REVIEW

**Comment by bigjosh** [comment]
Possible to bracket the LOGx() macros so they compile away when they are below the current logging level rather than checking `shouldLog()` at runtime?

**Comment by kenj1** [comment]
That's a good comment Josh.  I will look into adding that.

**Comment by kenj1** [comment]
Follow up question:
At this time, the base Print methods do not have a Macro like ability (as suggested) to have them compile away.  Would those base Print methods still be desired/used in lieu of a LogSerial printf-like ability?  E.g. keep them for backward compatibility with existing sketches?  

Would users want anything other than log (debug) macros that they can compile away?

**Comment by bigjosh** [comment]
I am looking for a way to keep the code pulled in by `xxxprintf()` and the `F()` strings out of the image when compiling for production since it will almost certainly not fit into a non-dev blink. 

It looks like you already suppress the individual logging commands when `LOG_SERIAL_INST` is not defined. So maybe something like this that not only covers up the logging calls but also keeps the Serial stuff from getting pulled in as well.

Atmel studio handles this by defining `DEBUG` when compiling debug versions and `NDEBUG` when compiling releases, but I'd hate to fold in an AS7 dependency now. Maybe we are careful to provide makefiles that match this convention?

**Comment by kenj1** [comment]
I have not heard the term "non-dev Blink" before.  What other Blink configurations (and sizes) are there?

My original thinking on tracing was a programmatic way of controlling the trace messages.  But I think for Blinks it makes more sense to just have a user definable level of log messages either in or out of the final compilation.  This slims down the new code even more.

I believe LogSerial covers all trace use-cases.  Is there a need for the base Print print methods anymore??  (Can those be slimmed down (phased out) too?).  Note, using both style print methods in a sketch can lead to compile time ambiguity (overlapping signatures).  I will add preprocessor warning if this situation is detected.

I will make the changes such that LogSerial macros are in or out based on a USE_LOG_LEVEL define.  Any direct calls to the print methods (i.e. not macros) would remain.  There will be 4 hierarchical log levels: LOG_ERROR, LOG_WARN, LOG_INFO, LOG_DEBUG (and a LOG_ALL as explicit (convenience) to include everything).

E.g. 
// Include only error log messages
#define USE_LOG_LEVEL   LOG_ERROR

-or-
// include error, warning and info log messages
#define USE_LOG_LEVEL LOG_INFO

**Comment by bigjosh** [comment]
>I have not heard the term "non-dev Blink" before. What other Blink configurations 
>(and sizes) are there?

The biggest difference between a dev blink and a retail blink will be configuration. Retail blinks come with a built in game and a bootstrap loads for downloading an additional game over IR. This means that any game that will run on a retail blink can only use about 1/3 of the flash.

**Comment by bigjosh** [comment]
> Is there a need for the base Print print methods anymore?? 

The thinking here was to match the idiomatic Arduino calls.  Don't get me wrong, the Arduino stuff is ugly... but people know it and are used to it so want to give people what they expect and reduce the surprise.

**Comment by bigjosh** [comment]
>There will be 4 hierarchical log levels: LOG_ERROR, LOG_WARN, LOG_INFO, LOG_DEBUG (and a >LOG_ALL as explicit (convenience) to include everything).

This is great and is similar to some familiar patterns like log4j.

**Comment by bigjosh** [comment]
>I will make the changes such that LogSerial macros are in or out based on a USE_LOG_LEVEL define. 
>Any direct calls to the print methods (i.e. not macros) would remain.

How about hiding the methods and making the macros the only proper way to make the calls?

I think makes explicit that the log level is a constant, ensures that everything goes away when the log level is NONE, and hides the method signatures from the base so you can rename them to avoid collisions.

**Comment by kenj1** [comment]
Is there a need to support a sketch that uses both forms of print methods (i.e. Print print methods (old style) and the new LogSerial (printf style)?  I can make changes to support both simultaneously but is there a need?

**Comment by kenj1** [comment]
I had thought about abstracting the names via macros for those reasons but it's not obvious to me the best way to make ensure the "only proper way to make calls" is via the macros (i.e. prevent direct method invocations and only access via macro).

**Comment by kenj1** [comment]
I've probably got some cobwebs to clear out since retiring years ago.  I've been scratching my head on how best to hide the methods and make macros the only proper way to make the calls.  

Will Blinks release the library source, or some form that's pre-compiled?  Pre-compiled has it's own issues/limitations (from what I've read).  If only library source is to be released than all approaches I've gone thru lead back to the fact that macros are inline and the implementation could be determined by a sufficiently inquisitive developer (i.e. knowing that they could directly call the LogSerial "print" method).  Warnings in the API doc could be added to discourage that but direct method invocation did not seem preventable.  I'm probably missing it.  Were you thinking of simply warning the user to only use the macros?  Or another approach?

**Comment by kenj1** [comment]
I am closing this pull and will resubmit in a bit w/ solution closer to what we discussed.

**Pull request closed without merging**
